### ISSUE TITLE
KSP 1.8 and 1.9 compatibility

### ISSUE THREAD

**Issue by linuxgurugamer** [Kopernicus/Kronometer#12]
any known problems?

**Comment by Sigma88** [comment]
none were reported as of now, but I haven't tested this on either 1.8.1 or 1.9.1 so that's why there is no release

**Comment by linuxgurugamer** [comment]
ok, thank you.
I'm actually using it in 1.8.1, but not sure what to be looking for, which is why I asked

**Comment by Sigma88** [comment]
well, what kronometer does is changing how the time is displayed.

if the time you see displayed has issues that could be a bug.

depends on the settings you are using
