### ISSUE TITLE
Days of Months are not happy with each other

### ISSUE THREAD

**Issue by Wallum** [Kopernicus/Kronometer#15]
![image](https://user-images.githubusercontent.com/6353826/106522988-6713da80-64d8-11eb-8960-ab9ad6e1bbb5.png)

Custom config setting to add in real world months/years (but with a shorter day period, hence "%useHomeDay = true" to match the Dimensions scaling I am using. As seen in the picture, and despite lockdown, I don't remember a "Feb 33rd". I don't know if I am being stupid or this is a bug but I have [linked (pastebin)](https://pastebin.com/B2UB4tim) config file too.

Feedback would be helpful

**Comment by Sigma88** [comment]
there was a syntax change I forgot to report,

`<D><Dth>` now refer to different values than before

`<D>` is the number of the day within the year, so at february 1st `<D>` will be `32`

`<Dth>` is the suffix for the day of the year, so for day `32` you will get `nd`

what you want is the day of the month, which is now written as `<Dm>` and the correct suffix is `<Dmth>`

**Comment by Sigma88** [comment]
does this fix your issue?

**Comment by Wallum** [comment]
Hello
Apologies for the late reply;
I've played a bit and it looks like it is working correctly changing the D/Dth to Dm/Dmth, cheers for your help

**Comment by Sigma88** [comment]
great!

closing this issue since it seems fixed, if you need more help feel free to re-open this issue or open a new one

have fun
