### ISSUE TITLE
CustomTime is not working correctly

### ISSUE THREAD

**Issue by MorePortal** [Kopernicus/Kronometer#16]
So I started playing with WhirligigWorld and got a very strange issue with Kronometer clock:

Here's CustomTime Node:

> CustomTime
	{
		Second
		{
			singular = second
			plural = seconds
			symbol = s
			value = 1.008
		}
		Minute
		{
			singular = minute
			plural = minutes
			symbol = m
			value = 60.48
		}
		Hour
		{
			singular = day
			plural = days
			symbol = d
			value = 2721.6
		}
		Day
		{
			singular = Fortnight
			plural = Fortnights
			symbol = F
			value = 38102.4
		}
		Year
		{
			singular = Year
			plural = Years
			symbol = Y
			value = 21485745.3766626416
		}
	}

In this config 1 hour (called day here) equals 45 minutes

Here's what happends ingame:
For some reason, UT "thinks" that 1 hour  = 60 minutes
But MET (correctly) gets 1 hour = 45 minutes

Also tested with clean install (only Kronometer installed) - same thing happens

What's wrong?

Logfile (on clean install): [Player.log](https://github.com/Kopernicus/Kronometer/files/6560576/Player.log)

Here is example of what happens (using KerbalAlarmClock):

![Скриншот 2021-05-28 13 56 20](https://user-images.githubusercontent.com/19516422/119978924-e9159b00-bfc2-11eb-9c11-438461707af2.png)

**Comment by MorePortal** [comment]
Whoops, that was just an outdated Kronometer

**Comment by Sigma88** [comment]
sorry for the late reply,
glad you worked it out anyways
